import pathlib,os,json,threading,http.server,functools,traceback,sys
from playwright.sync_api import sync_playwright,expect
ROOT=pathlib.Path(__file__).resolve().parent.parent
OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT/'dist')))
threading.Thread(target=server.serve_forever,daemon=True).start()
URL=(os.getenv('IFC_TEST_URL') or f'http://127.0.0.1:{server.server_port}/')+'?test=1'
browsers=[]
results={'tests':[],'page_errors':[]}
def check(name,fn):
    fn();results['tests'].append({'name':name,'passed':True});print('PASS',name,flush=True)
def assert_equal(actual,expected):
    assert actual==expected,f'{actual!r} != {expected!r}'
def assert_true(actual,message):
    assert actual,message
failed=False
try:
    with sync_playwright() as p:
        candidates=list((pathlib.Path.home()/'AppData/Local/ms-playwright').glob('chromium-*/chrome-win64/chrome.exe'))
        executable=os.getenv('CHROME_PATH') or (str(sorted(candidates)[-1]) if candidates else None)
        options={'headless':True,'args':['--enable-unsafe-swiftshader'],'viewport':{'width':1600,'height':1050},'accept_downloads':True}
        if executable:options['executable_path']=executable
        browser=p.chromium.launch(**{k:v for k,v in options.items() if k not in ['viewport','accept_downloads']});browsers.append(browser)
        context=browser.new_context(viewport=options['viewport'],accept_downloads=True)
        page=context.new_page();page.set_default_timeout(20000)
        page.on('pageerror',lambda e:results['page_errors'].append(str(e)))
        page.goto(URL,wait_until='domcontentloaded')
        check('version 2.0 visible',lambda:expect(page.locator('#release-version')).to_have_text('v2.0',timeout=10000))
        check('arranque sin pantalla vacia',lambda:page.wait_for_function('document.documentElement.dataset.appState === "ready"',timeout=90000))
        check('canvas creado',lambda:expect(page.locator('canvas')).to_have_count(1))
        check('herramientas v2 presentes',lambda:expect(page.locator('#workspace-v2')).to_be_visible())
        check('estado vacio del tablero',lambda:expect(page.locator('#catalog-total')).to_have_text('0'))
        page.on('dialog',lambda dialog:dialog.accept())
        page.locator('bim-button[label="Cargar ejemplo"]').click()
        check('IFC ejemplo carga con geometria',lambda:page.wait_for_function('Number(document.querySelector("#catalog-total").textContent)>0 && document.querySelector("#workspace-v2").dataset.indexState==="ready"',timeout=90000))
        original=page.evaluate('window.__IFC_TEST.workspace.records.length')
        results['example_count']=original
        expected=page.evaluate('async()=>{let n=0;for(const m of window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.FragmentsManager).list.values())n+=(await m.getItemsIdsWithGeometry()).length;return n;}')
        check('tablero concuerda con geometria real',lambda:assert_equal(original,expected))
        floor=page.evaluate('window.__IFC_TEST.workspace.records.find(r=>r.guid==="3zR0BOEcLADRKln4HYporH")')
        check('nivel coincide con IFC fuente',lambda:assert_equal(floor['level'],'00 groundfloor'))
        check('Pset coincide con IFC fuente',lambda:assert_equal(floor['properties'].get('Pset_SlabCommon.FireRating'),'REI30'))
        check('cantidad coincide con IFC fuente',lambda:assert_true(abs(floor['properties'].get('Qto_SlabBaseQuantities.NetVolume',0)-6.437500000000378)<1e-8,'Cantidad perdida o alterada'))
        page.locator('#filter-propertyName').select_option('Pset_SlabCommon.FireRating');page.locator('#filter-propertyValue').fill('REI30')
        check('filtro propiedad coincide con catalogo',lambda:assert_equal(int(page.locator('#filter-count').inner_text()),page.evaluate('window.__IFC_TEST.workspace.records.filter(r=>String(r.properties["Pset_SlabCommon.FireRating"]).toLowerCase().includes("rei30")).length')))
        page.locator('#filter-clear').click()
        page.locator('#filter-category').select_option('IFCSLAB')
        slabs=int(page.locator('#filter-count').inner_text())
        check('filtro IFCSLAB positivo',lambda:assert_true(slabs>0,'Sin losas'))
        page.locator('#filter-isolate').click()
        page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        visible=page.evaluate('async()=>{let n=0;for(const m of window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.FragmentsManager).list.values())n+=(await m.getItemsByVisibility(true)).length;return n;}')
        check('aislamiento solo deja coincidencias visibles',lambda:assert_equal(visible,slabs))
        page.locator('#filter-show').click();page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        page.locator('#filter-text').fill('texto_imposible_129018')
        check('filtros combinados AND',lambda:expect(page.locator('#filter-count')).to_have_text('0'))
        page.locator('#filter-text').fill('')
        page.get_by_text('Consultas guardadas',exact=True).click()
        page.locator('#query-name').fill('Losas para clase');page.locator('#query-save').click()
        page.locator('#filter-clear').click();page.locator('#query-list').select_option('0');page.locator('#query-load').click()
        check('consulta guardada recupera filtro',lambda:expect(page.locator('#filter-count')).to_have_text(str(slabs)))
        page.locator('#filter-select').click();page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        selected=page.evaluate('Object.values(window.__IFC_TEST.components.get(window.__IFC_TEST.OBF.Highlighter).selection.select).reduce((n,s)=>n+s.size,0)')
        check('seleccion vinculada al 3D',lambda:assert_equal(selected,slabs))
        with page.expect_download() as csv_download:page.locator('#filter-export').click()
        csv_path=OUT/'elementos-v2.csv';csv_download.value.save_as(str(csv_path))
        import csv
        with csv_path.open(encoding='utf-8-sig',newline='') as f:csv_rows=list(csv.DictReader(f))
        check('CSV cuenta todos los resultados',lambda:assert_equal(len(csv_rows),slabs))
        page.locator('#tab-quality').click();page.locator('#rule-category').select_option('IFCSLAB')
        page.locator('#rule-name').fill('Nombre presente');page.locator('#rule-add').click();page.locator('#quality-run').click()
        check('regla positiva real',lambda:expect(page.locator('#quality-summary')).to_contain_text(f'{slabs} cumple / 0 no cumple'))
        page.locator('#rule-name').fill('Nombre imposible');page.locator('#rule-operator').select_option('equals');page.locator('#rule-expected').fill('IMPOSIBLE_129018');page.locator('#rule-add').click();page.locator('#quality-run').click()
        check('regla negativa real',lambda:expect(page.locator('#quality-summary')).to_contain_text(f'{slabs} cumple / {slabs} no cumple'))
        with page.expect_download() as quality_download:page.locator('#quality-export').click()
        quality_path=OUT/'revision-v2.csv';quality_download.value.save_as(str(quality_path))
        with quality_path.open(encoding='utf-8-sig',newline='') as f:quality_rows=list(csv.DictReader(f))
        check('CSV revision contiene todas las comprobaciones',lambda:assert_equal(len(quality_rows),slabs*2))
        page.locator('#quality-color').click();page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        check('colorear repetidamente conserva eventos',lambda:page.evaluate('async()=>{const t=window.__IFC_TEST;const results=t.workspace.records.filter(r=>r.category==="IFCSLAB").map(element=>({element,pass:false}));for(let i=0;i<3;i++)await t.workspace.colorResults(results);}'))
        check('coloreado repetido conserva elementos',lambda:assert_equal(page.evaluate('Object.values(window.__IFC_TEST.components.get(window.__IFC_TEST.OBF.Highlighter).selection["revision-no-cumple"]).reduce((n,s)=>n+s.size,0)'),slabs))
        page.locator('#quality-select').click();page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        check('fallos se seleccionan',lambda:assert_equal(page.evaluate('Object.values(window.__IFC_TEST.components.get(window.__IFC_TEST.OBF.Highlighter).selection.select).reduce((n,s)=>n+s.size,0)'),slabs))
        page.evaluate('async()=>{await window.__IFC_TEST.world.camera.projection.set("Orthographic");window.__IFC_TEST.world.renderer.postproduction.updateCamera();}')
        check('proyeccion ortografica funcional',lambda:assert_equal(page.evaluate('window.__IFC_TEST.world.camera.projection.current'),'Orthographic'))
        page.locator('bim-button[label="Agregar"]').click()
        page.wait_for_function('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.size===1')
        page.locator('#tab-catalog').click();page.locator('#filter-isolate').click();page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        page.locator('#tab-sessions').click();page.locator('#session-name').fill('Smoke v2 real')
        page.locator('#session-save').click()
        check('guardar sesion verificado',lambda:expect(page.locator('#session-status')).to_contain_text('Guardada y verificada',timeout=60000))
        with page.expect_download(timeout=60000) as download:page.locator('#session-export').click()
        export=OUT/'sesion-ifc-v2.json';download.value.save_as(str(export))
        snapshot=json.loads(export.read_text(encoding='utf8'));results['session_models']=len(snapshot['models'])
        check('JSON contiene modelo real',lambda:assert_true(len(snapshot['models'][0]['bytes'])>1000,'No incluye modelo'))
        check('JSON incluye consultas',lambda:assert_equal(len(snapshot['state'].get('queries',[])),1))
        check('JSON incluye vistas',lambda:assert_equal(len(snapshot['state']['views']),1))
        check('JSON conserva colores no vacios',lambda:assert_true(sum(len(g['items']) for g in snapshot['state']['colors'])>0,'Colores perdidos'))
        page.screenshot(path=str(OUT/'v2-session.png'),full_page=True)
        page.reload(wait_until='domcontentloaded');page.wait_for_function('document.documentElement.dataset.appState==="ready"',timeout=90000)
        check('recarga empieza sin modelos',lambda:expect(page.locator('#catalog-total')).to_have_text('0'))
        page.locator('#tab-sessions').click();page.wait_for_function('document.querySelector("#session-list").options.length>1')
        session_id=page.locator('#session-list').evaluate('(node)=>node.options[1].value');page.locator('#session-list').select_option(session_id);page.locator('#session-load').click()
        check('sesion reabre tras recargar',lambda:expect(page.locator('#session-status')).to_contain_text('Recuperada:',timeout=90000))
        check('geometria restaurada',lambda:expect(page.locator('#catalog-total')).to_have_text(str(original)))
        check('proyeccion recuperada',lambda:assert_equal(page.evaluate('window.__IFC_TEST.world.camera.projection.current'),'Orthographic'))
        check('reglas recuperadas',lambda:assert_equal(page.evaluate('window.__IFC_TEST.workspace.rules.length'),2))
        check('consulta recuperada',lambda:assert_equal(page.evaluate('window.__IFC_TEST.workspace.queries.length'),1))
        check('vistas reconstruidas en interfaz',lambda:assert_equal(page.evaluate('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.size'),1))
        restored=page.evaluate('async()=>window.__IFC_TEST.workspace.capture("probe")')
        check('ocultos recuperados',lambda:assert_equal(len(restored['state']['hidden']),len(snapshot['state']['hidden'])))
        check('camara recuperada',lambda:assert_equal(restored['state']['camera'],snapshot['state']['camera']))
        check('seleccion recuperada',lambda:assert_equal(len(restored['state']['selection']),len(snapshot['state']['selection'])))
        check('colores recuperados',lambda:assert_equal(sum(len(x['items']) for x in restored['state']['colors']),sum(len(x['items']) for x in snapshot['state']['colors'])))
        page.locator('#session-import').set_input_files(str(export))
        check('importacion JSON restaura',lambda:expect(page.locator('#session-status')).to_contain_text('Importada y guardada:',timeout=90000))
        recolored=json.loads(export.read_text(encoding='utf8'))
        for group in recolored['state']['colors']:group['color']='#0000ff'
        color_file=OUT/'sesion-otro-color.json';color_file.write_text(json.dumps(recolored),encoding='utf8')
        page.locator('#session-import').set_input_files(str(color_file));page.wait_for_function('document.querySelector("#workspace-v2").getAttribute("aria-busy")!=="true"')
        colors=page.evaluate('async()=>{const s=await window.__IFC_TEST.workspace.capture("probe");return [...new Set(s.state.colors.map(g=>g.color))];}')
        check('importar otra sesion actualiza el color real',lambda:assert_equal(colors,['#0000ff']))
        damaged=json.loads(export.read_text(encoding='utf8'));damaged['models'][0]['bytes']='aW52YWxpZA=='
        bad=OUT/'sesion-danada.json';bad.write_text(json.dumps(damaged),encoding='utf8')
        page.locator('#session-import').set_input_files(str(bad))
        check('fingerprint alterado rechazado',lambda:expect(page.locator('#feedback')).to_contain_text('huella',timeout=30000))
        check('sesion invalida no borra modelo actual',lambda:expect(page.locator('#catalog-total')).to_have_text(str(original)))
        page.evaluate('()=>{const dt=new DataTransfer();dt.items.add(new File(["not IFC"],"invalido.ifc"));document.querySelector("bim-viewport").dispatchEvent(new DragEvent("drop",{dataTransfer:dt,bubbles:true}));}')
        check('IFC invalido da error visible',lambda:expect(page.locator('#feedback')).to_contain_text('cabecera',timeout=30000))
        page.locator('bim-button[label="Cargar Graderías"]').click()
        check('segundo IFC carga',lambda:page.wait_for_function('Number(document.querySelector("#catalog-total").textContent)>'+str(original)+' && document.querySelector("#workspace-v2").dataset.indexState==="ready"',timeout=90000))
        results['federated_count']=int(page.locator('#catalog-total').inner_text())
        page.locator('#tab-catalog').click();page.screenshot(path=str(OUT/'v2-tablero.png'),full_page=True)
        check('sin errores JS en flujos reales',lambda:assert_equal(results['page_errors'],[]))
        context.browser.close()
        # Cada error de recursos se prueba en un contexto limpio.
        for resource in ['fragments-worker.mjs','wasm/web-ifc.wasm']:
            browser=p.chromium.launch(**{k:v for k,v in options.items() if k not in ['viewport','accept_downloads']})
            browsers.append(browser)
            ctx=browser.new_context(viewport=options['viewport'])
            ctx.route('**/'+resource, lambda route: route.fulfill(status=404,body='missing'))
            errorpage=ctx.new_page();errorpage.goto(URL,wait_until='domcontentloaded')
            check('fallo visible: '+resource,lambda:expect(errorpage.locator('#retry-start')).to_be_visible(timeout=90000))
            check('estado error: '+resource,lambda:errorpage.wait_for_function('document.documentElement.dataset.appState === "error"'))
            browser.close()
        for resource in ['fragments-worker.mjs','wasm/web-ifc.wasm']:
            original_bytes=(ROOT/'dist'/resource).read_bytes();corrupt=bytes([original_bytes[0]^1])+original_bytes[1:]
            browser=p.chromium.launch(**{k:v for k,v in options.items() if k not in ['viewport','accept_downloads']});browsers.append(browser)
            ctx=browser.new_context(viewport=options['viewport']);ctx.route('**/'+resource,lambda route:route.fulfill(status=200,body=corrupt))
            errorpage=ctx.new_page();errorpage.goto(URL,wait_until='domcontentloaded')
            errorpage.wait_for_function('document.documentElement.dataset.appState!=="loading"',timeout=90000)
            check('corrupcion 200 mismo tamaño rechazada: '+resource,lambda:assert_equal(errorpage.evaluate('document.documentElement.dataset.appState'),'error'))
            check('motivo integridad visible: '+resource,lambda:expect(errorpage.locator('#startup-phase')).to_contain_text('integridad'))
            browser.close()
except Exception as e:
    failed=True;results['failure']=str(e);print(traceback.format_exc(),flush=True)
finally:
    for browser in browsers:
        try:browser.close()
        except Exception:pass
    server.shutdown();server.server_close();(OUT/'smoke-v2.json').write_text(json.dumps(results,indent=2),encoding='utf8');print(json.dumps(results,indent=2),flush=True)
if failed:sys.exit(1)
