"""Regresión real de cámaras/vistas; HTTP y Chromium efímeros."""
import pathlib,os,json,threading,http.server,functools,traceback,sys
from playwright.sync_api import sync_playwright,expect
ROOT=pathlib.Path(__file__).resolve().parent.parent
OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT/'dist')))
threading.Thread(target=server.serve_forever,daemon=True).start()
report={'tests':[],'page_errors':[]};failed=False

def check(name,fn):
    fn();report['tests'].append({'name':name,'passed':True});print('PASS',name,flush=True)
def same(a,b):assert a==b,f'{a!r} != {b!r}'
def nav(page,section):
    button=page.locator('#nav-'+section)
    if button.count():button.click()
def ready(page):page.wait_for_function('document.querySelector("#views-panel")?.getAttribute("aria-busy")!=="true" && document.querySelector("#workspace-v2")?.getAttribute("aria-busy")!=="true"')
try:
    with sync_playwright() as p:
        candidates=sorted((pathlib.Path.home()/'AppData/Local/ms-playwright').glob('chromium-*/chrome-win64/chrome.exe'))
        with p.chromium.launch(headless=True,executable_path=os.getenv('CHROME_PATH') or str(candidates[-1]),args=['--enable-unsafe-swiftshader']) as browser:
            context=browser.new_context(viewport={'width':1366,'height':768},accept_downloads=True)
            page=context.new_page();page.set_default_timeout(20000);page.on('pageerror',lambda e:report['page_errors'].append(str(e)))
            page.goto(f'http://127.0.0.1:{server.server_port}/?test=1');page.wait_for_function('document.documentElement.dataset.appState==="ready"',timeout=90000)
            nav(page,'models');page.locator('bim-button[label="Cargar ejemplo"]').click()
            page.wait_for_function('Number(document.querySelector("#catalog-total").textContent)>0&&document.querySelector("#workspace-v2").dataset.indexState==="ready"',timeout=90000)
            nav(page,'views')
            if page.locator('#view-create').count():page.locator('#view-create').click();ready(page)
            else:
                page.locator('bim-button[label="Agregar"]').click();page.wait_for_function('!document.querySelector("bim-button[label=Agregar]").loading')
            moved=page.evaluate('async()=>{const c=window.__IFC_TEST.world.camera;await c.controls.setLookAt(61,52,57,3,1,6,false);c.controls.update(1);c.three.updateMatrixWorld(true);return {eye:c.three.position.toArray(),target:c.controls.getTarget(c.three.position.clone()).toArray(),projection:c.projection.current};}')
            if page.locator('[data-action="update"]').count():page.locator('[data-action="update"]').first.click();ready(page)
            else:
                page.locator('bim-button[label="Agregar"]').click();page.wait_for_function('!document.querySelector("bim-button[label=Agregar]").loading')
                print(page.locator('bim-panel-section[label="Vistas guardadas"]').inner_html(),flush=True)
                page.locator('bim-panel-section[label="Vistas guardadas"] bim-button[icon="prime:ellipsis-v"]').first.click();page.locator('bim-button[label="Update Camera"]:visible').click()
                page.wait_for_timeout(700)
            snap=page.evaluate('async()=>window.__IFC_TEST.workspace.capture("update-camera")')
            check('actualizar conserva la cámara nueva en la sesión',lambda:same(snap['state']['views'][0]['camera'],moved))
            page.evaluate('async()=>{const t=window.__IFC_TEST;await t.workspace.select(t.workspace.records);await t.workspace.colorResults(t.workspace.records.map(element=>({element,pass:false})));window.__guidCalls=0;const f=t.components.get(t.OBC.FragmentsManager);window.__originalGuids=f.modelIdMapToGuids.bind(f);f.modelIdMapToGuids=async(...args)=>{window.__guidCalls++;return window.__originalGuids(...args);};}')
            page.locator('#view-create').click();ready(page)
            selected=page.evaluate('()=>{const t=window.__IFC_TEST;const v=[...t.components.get(t.OBC.Viewpoints).list.values()].at(-1);return {selection:v.selectionComponents.size,colors:v.componentColors.size,calls:window.__guidCalls};}')
            check('vista conserva selección real',lambda:same(selected['selection'],13))
            check('estilo select no duplica color persistente',lambda:same(selected['colors'],1))
            check('mapas idénticos se convierten una sola vez',lambda:same(selected['calls'],1))
            check('cambios sin guardar visibles junto al guardado',lambda:expect(page.locator('#work-status')).to_contain_text('Cambios sin guardar'))
            check('guardar no genera PNG',lambda:same(page.evaluate('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).snapshots.size'),0))
            check('nombres automáticos distintos',lambda:same(page.evaluate('[...window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.values()].map(v=>v.title)'),['Vista 1','Vista 2']))
            page.once('dialog',lambda d:d.accept('Fachada este'));page.locator('[data-action="rename"]').first.click();ready(page)
            check('renombrar aparece en la lista',lambda:expect(page.locator('#view-list')).to_contain_text('Fachada este'))
            page.once('dialog',lambda d:d.dismiss());page.locator('[data-action="delete"]').first.click();ready(page)
            check('cancelar borrado conserva las vistas',lambda:same(page.evaluate('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.size'),2))
            page.evaluate('async()=>{const t=window.__IFC_TEST;await t.workspace.isolate(t.workspace.records.filter(r=>r.category==="IFCSLAB"));}')
            visible=lambda:page.evaluate('async()=>{let n=0;for(const m of window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.FragmentsManager).list.values())n+=(await m.getItemsByVisibility(true)).length;return n;}')
            before=visible();page.locator('[data-action="open"]').first.click();ready(page)
            check('abrir encuadre conserva el aislamiento actual',lambda:same(visible(),before))
            page.locator('#quick-session-save').click();ready(page)
            check('guardado rápido confirmado',lambda:expect(page.locator('#session-status')).to_contain_text('Guardada y verificada',timeout=60000))
            check('guardado confirmado limpia indicador',lambda:expect(page.locator('#work-status')).to_contain_text('Guardada en este navegador'))
            nav(page,'workspace');page.locator('#tab-catalog').click();page.locator('#filter-text').fill('floor')
            check('filtro cambia estado de guardado',lambda:expect(page.locator('#work-status')).to_contain_text('Cambios sin guardar'))
            page.locator('#tab-sessions').click()
            with page.expect_download(timeout=60000) as dl:page.locator('#session-export').click()
            exported=OUT/'v21-views-session.json';dl.value.save_as(str(exported));ready(page)
            check('exportar copia no declara guardado local',lambda:expect(page.locator('#work-status')).to_contain_text('Cambios sin guardar'))
            exported_data=json.loads(exported.read_text(encoding='utf8'))
            check('JSON conserva el nombre renombrado',lambda:same(exported_data['state']['views'][0]['name'],'Fachada este'))
            page.evaluate('()=>{window.__oldOpen=indexedDB.open.bind(indexedDB);indexedDB.open=()=>{throw new Error("Fallo simulado de almacenamiento");};}')
            page.locator('#session-save').click();ready(page)
            check('fallo de almacenamiento no limpia indicador',lambda:expect(page.locator('#work-status')).to_contain_text('Cambios sin guardar'))
            check('fallo de guardado visible en contexto',lambda:expect(page.locator('#workspace-operation-status')).to_contain_text('No se pudo abrir el almacén local'))
            page.evaluate('()=>{indexedDB.open=window.__oldOpen;}')
            nav(page,'views')
            page.evaluate('()=>{window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.FragmentsManager).modelIdMapToGuids=async()=>{throw new Error("GUID no disponible");};}')
            old=page.evaluate('()=>{const v=[...window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.values()][0];return {camera:v.customData.sessionCamera,title:v.title};}')
            page.locator('[data-action="update"]').first.click();ready(page)
            check('error al actualizar no cambia encuadre previo',lambda:same(page.evaluate('()=>{const v=[...window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.values()][0];return {camera:v.customData.sessionCamera,title:v.title};}'),old))
            page.locator('#view-create').click();ready(page)
            check('error de creación no deja fila incompleta',lambda:same(page.evaluate('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.size'),2))
            check('error de vista visible en contexto',lambda:expect(page.locator('#views-status')).to_contain_text('GUID no disponible'))
            page.evaluate('()=>{const t=window.__IFC_TEST;t.components.get(t.OBC.FragmentsManager).modelIdMapToGuids=window.__originalGuids;window.__oldUpdate=t.OBC.Viewpoint.prototype.updateCamera;t.OBC.Viewpoint.prototype.updateCamera=function(...args){return new Promise((resolve,reject)=>{window.__releaseView=()=>window.__oldUpdate.apply(this,args).then(resolve,reject);});};}')
            page.locator('#view-create').evaluate('(b)=>{b.click();b.click();}')
            check('doble clic queda bloqueado durante operación',lambda:expect(page.locator('#view-create')).to_be_disabled())
            check('no se muestra fila pendiente',lambda:same(page.locator('.saved-view-row').count(),2))
            page.wait_for_function('document.querySelector("#views-panel").getAttribute("aria-busy")==="false"',timeout=15000)
            check('timeout da mensaje y permite reintentar',lambda:expect(page.locator('#views-status')).to_contain_text('tardó demasiado'))
            page.evaluate('async()=>{window.__releaseView();await new Promise(r=>setTimeout(r,100));window.__IFC_TEST.OBC.Viewpoint.prototype.updateCamera=window.__oldUpdate;}')
            check('resolución tardía no vuelve a añadir la vista',lambda:same(page.evaluate('window.__IFC_TEST.components.get(window.__IFC_TEST.OBC.Viewpoints).list.size'),2))
            page.locator('#quick-session-save').click();ready(page)
            expect(page.locator('#session-status')).to_contain_text('Guardada y verificada',timeout=60000)
            saved_id=page.locator('#session-list').input_value()
            page.once('dialog',lambda d:d.accept());page.reload();page.wait_for_function('document.documentElement.dataset.appState==="ready"',timeout=90000)
            nav(page,'workspace');page.locator('#tab-sessions').click();page.locator('#session-list').select_option(saved_id);page.locator('#session-load').click();ready(page)
            expect(page.locator('#session-status')).to_contain_text('Recuperada:',timeout=90000)
            restored=page.evaluate('async()=>window.__IFC_TEST.workspace.capture("recuperada")')
            check('recarga recupera cámara actualizada de la vista',lambda:same(restored['state']['views'][0]['camera'],moved))
            check('recarga recupera nombres',lambda:same(restored['state']['views'][0]['name'],'Fachada este'))
            nav(page,'views');check('lista recuperada muestra nombre correcto',lambda:expect(page.locator('#view-list')).to_contain_text('Fachada este'))
            page.screenshot(path=str(OUT/'v21-views.png'),full_page=True)
            check('sin errores JS',lambda:same(report['page_errors'],[]))
except Exception as e:
    failed=True;report['failure']=str(e);print(traceback.format_exc(),flush=True)
finally:
    server.shutdown();server.server_close();(OUT/'smoke-views-v21.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf8')
if failed:sys.exit(1)
